# Generated by Django 5.1.5 on 2025-04-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='budget_highest',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='budget_lowest',
        ),
    ]
