# Generated by Django 5.1.5 on 2025-04-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_usersettings'),
        ('accounts', '0002_rename_budget_highest_usersettings_budget_and_more'),
    ]

    operations = [
    ]
