# Generated by Django 5.2 on 2025-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbreakuser',
            name='restaurant_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
