# Generated by Django 5.2 on 2025-04-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workbreakuser_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbreakuser',
            name='restaurant_name',
        ),
    ]
