# Generated by Django 5.1.7 on 2025-04-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
