# Generated by Django 5.2 on 2025-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_userreview_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
