# Generated by Django 5.2 on 2025-04-18 20:15

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='workbreak.png', upload_to=user.models.get_upload_path),
        ),
    ]
