# Generated by Django 5.2 on 2025-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cuisines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
