# Generated by Django 5.2 on 2025-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_restaurantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(default='Moderate', max_length=255),
            preserve_default=False,
        ),
    ]
