# Generated by Django 5.2 on 2025-04-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(default='INEXPENSIVE', max_length=255),
        ),
    ]
