# Generated by Django 5.2 on 2025-04-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userprofile_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
