# Generated by Django 5.2 on 2025-04-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurant_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
