# Generated by Django 5.2 on 2025-04-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_restaurant_delete_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
